mcq_platform/mcq/urls.py
from django.conf.urls import url

from . import views

# urlpatterns = [
#     url(r'^$', views.index, name='index'),
#     # ex: /polls/5/
#     url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
#     # ex: /polls/5/vote/
#     url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
# ]

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^asstlist/$', views.AsstListView.as_view(), name='asstlist'),
    url(r'^asstresult/$', views.AsstResultView.as_view(), name='asstresult'),
    url(r'^asstdetail/(?P<assessment_id>[0-9]+)/$', views.UserAsstDetail, name='userasstdetail'),
    url(r'^asstresult/(?P<assessment_id>[0-9]+)/$', views.UserAsstResult, name='userasstresult'),

    url(r'^admin/$', views.AdminIndex, name='mcqadmin'),
    
    url(r'^admin/labellist/$', views.SubjectListView, name='subjectlist'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^admin/labellist/create_label/$',views.SubjectCreation,name = 'labelcreation'),
    url(r'^admin/labellist/edit/(?P<label_id>[0-9]+)/$',views.LabelEdit,name = 'labeledit'),


    url(r'^index/$', views.index, name='index'),
    url(r'^hello/$', views.hello, name='hello'),

    url(r'^profile/(.+)/$', views.profile,name="userprofile"),

    url(r'^admin/mcqcollection/$', views.McqCollectionView.as_view(), name='mcqcollection'),
    url(r'^admin/mcqcollection/create_mcq/$',views.McqOption,name = 'mcqoption'),
    url(r'^admin/mcqcollection/edit/(?P<question_id>[0-9]+)/$',views.McqEdit,name = 'mcqedit'),
    url(r'^admin/mcqcollection/replica/(?P<asst_id>[0-9]+)/(?P<question_id>[0-9]+)/$',views.McqReplica,name = 'mcqreplica'),
   
    url(r'^admin/mcqcollection/create_mcq/(?P<option>[0-3]{1})/$',views.McqCreation,name = 'mcqcreation'),
 
    url(r'^admin/bundlecollection/create_bundle/$',views.BundleCreation,name = 'bundlecreation'),
    url(r'^admin/bundlecollection/$', views.BundleCollectionView.as_view(), name='bundlecollection'),
    url(r'^admin/bundlecollection/(?P<bundle_id>[0-9]+)/$',views.BundleDetail,name = 'bundlecdetail'),
    url(r'^admin/bundlecollection/edit/(?P<bundle_id>[0-9]+)/$',views.BundleEdit,name = 'bundleedit'),
  
    url(r'^admin/asstcollection/create_asst/$',views.AsstCreation,name = 'asstcreation'),
    url(r'^admin/asstallocation/$',views.AsstAllocation,name = 'asstallocation'),
    url(r'^admin/asstcollection/$', views.AsstCollectionView.as_view(), name='asstcollection'),
    url(r'^admin/asstcollection/edit/(?P<asst_id>[0-9]+)/$',views.AsstEdit,name = 'asstedit'),

    url(r'^admin/statistics/mcq/(?P<question_id>[0-9]+)/$', views.McqStatsView, name='mcqstats'),
    url(r'^admin/statistics/asst/(?P<assessment_id>[0-9]+)/$', views.AsstStatsView, name='asststats'),
    url(r'^ajax_deal/$',views.ajax_deal,name='ajax'),
    url(r'^ccc/$',views.ccc,name="ccc"),

    url(r'^tt/$',views.tt,name="tt"),

    url(r'^embed/(?P<question_id>[0-9]+)/$', views.EmbedMcq, name='embedmcq'),

]

mcq_platform/mcq_platform/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'mcq_platform.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^mcq/', include('mcq.urls',namespace ="mcq")),
    url(r'^admin/', include(admin.site.urls)),
]

mcq_platform/mcq/models.py
from django.db import models
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.


# For storing user profile
from django.contrib.auth.models import User
from django.db.models.signals import post_save




class UserProfile(models.Model):
    # This field is required.
    user = models.OneToOneField(User)

    # Other fields here
    num_completed_asst = models.IntegerField(default = 0)
    num_incomplete_asst = models.IntegerField(default = 0)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)


class Category(models.Model):
    category_code = models.CharField(max_length = 8,default = "11")
    category_name = models.CharField(max_length = 100)

    def __str__(self):              # __unicode__ on Python 2
        return self.category_code

ASST_CHOICES = (
    (0, 'practical exercise'),
    (1, 'formal exam'),
)

ASST_STATUS = (
    (0, 'OPEN'),
    (1, 'CLOSED'),
)

QUESTION_TYPES = (
    (0,'Single Answers'),
    (1,'Multiple Answers'),
    (2,'True/False'),
    (3,'Input'),
    (4,'undefined')
)

#feedback
class Question(models.Model):
    category = models.ManyToManyField(Category)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    question_type = models.IntegerField(choices = QUESTION_TYPES,default = 0)
    correct_answer = models.CharField(max_length =100,default=0)
    explanation = models.CharField(max_length =100,default="undefined")
    input_answer = models.CharField(max_length = 100,default=0)
    hints = models.CharField(max_length =100,default="No hints.")
    is_replica = models.BooleanField(default=False)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):              # __unicode__ on Python 2
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question)    
    answer_code = models.CharField(max_length = 10)
    is_correct = models.BooleanField(default= False)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):              # __unicode__ on Python 2
        return self.choice_text +" "+str(self.votes)

class PublicResult(models.Model):
    question = models.ForeignKey(Question)
    num_of_correct_attempts = models.IntegerField(default=0)
    num_of_incorrect_attempts = models.IntegerField(default=0)
    def __str__(self):              # __unicode__ on Python 2
        return self.question.question_text


def create_question(sender, instance, created, **kwargs):
    if created:
        PublicResult.objects.create(question=instance)

post_save.connect(create_question, sender=Question)

#total score out of
class Bundle(models.Model):
    question = models.ManyToManyField(Question)
   # category = models.ForeignKey(Category)
    bundle_name = models.CharField(max_length = 100)
    bundle_desc = models.CharField(max_length = 200,default="undefined")
    pub_date = models.DateTimeField('date published')
    total_question_num = models.IntegerField(default=0)
   # bundle_type = models.IntegerField(choices = BUNDLE_CHOICES,default = 0)
    #question_total_num = models.IntegerField(default = 1)
    #total_allocated = models.IntegerField(default = 0)
    #completed_num = models.IntegerField(default = 0)
    #pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.bundle_name



class Assessment(models.Model):
    question = models.ManyToManyField(Question, related_name='asstquestion')
    publisher = models.ForeignKey(User)
    category = models.ForeignKey(Category,null=True)
    assessment_name = models.CharField(max_length = 100,default=0)
    assessment_type = models.IntegerField(choices = ASST_CHOICES,default = 0)
    assessment_description = models.CharField(max_length = 200,default= "undefined")
    duration = models.IntegerField(default = 0)#mins  
    mcq_num = models.IntegerField(default = 0)
    points = models.IntegerField(default = 0)
    pub_date = models.DateTimeField('date published',default=None)
    deadline = models.DateTimeField('deadline')
    status = models.IntegerField(choices = ASST_STATUS,default = 0)
    


    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.assessment_name

class ChoiceAsstStats(models.Model):
    choice = models.ForeignKey(Choice)
    question = models.ForeignKey(Question)
    asst = models.ForeignKey(Assessment)
    votes = models.IntegerField(default=0)
    def __str__(self):              # __unicode__ on Python 2
        return self.choice.choice_text

class AssessmentQuestion(models.Model):
    asst_question = models.ForeignKey(Assessment)
    question = models.ForeignKey(Question)
    question_type = models.IntegerField(default=4)
   



class QuestionAttempt(models.Model):
    assessment = models.ForeignKey(Assessment)
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    user_answer = models.CharField(max_length = 10)
    is_correct = models.NullBooleanField(null=True)
    def __str__(self):
        return self.assessment.assessment_name + " " + self.user.username + " " + str(self.question.pk)


class AsstResult(models.Model):
    assessment = models.ForeignKey(Assessment)
    user = models.ForeignKey(User)
    score = models.IntegerField(default = 0)
    grade = models.CharField(max_length = 50,default="Undefined" )
    def __str__(self):
        return str(self.user.username)+"-"+str(self.assessment.assessment_name)



class group(models.Model):
    group_name = models.CharField(max_length = 20)
    creation_date = models.DateTimeField('date published')


class AllocationRecord(models.Model):
    asst = models.ForeignKey(Assessment)
    staff = models.ForeignKey(User)
    when = models.DateTimeField('Date allocated')
    def __str__(self):
        return str(self.staff.username)+"-"+str(self.asst.assessment_name)

class AssignedAsst(models.Model):
    asst = models.ForeignKey(Assessment)
    user = models.ForeignKey(User, related_name='to_user')
    from_user = models.ForeignKey(User, related_name='from_user')
    is_done = models.BooleanField(default= False) 
    def __str__(self):
        return (str(self.user.pk)+str(self.asst.assessment_name))

    def getAsstName(self):
        return str(self.asst.assessment_name)

    def dayCounter(self):
        left = self.asst.deadline - timezone.now()

        if timezone.now() < self.asst.deadline :
            if(left.days > 0):
                return str(left.days) + " day(s) left"
            elif ((left.seconds//3600) >0):
                return str((left.seconds//3600)) + " hr(s) left"
            elif ((left.seconds//60)%60 >0):
                return str((left.seconds//60)%60 ) + " min(s) left"
            else:
                return "EXPIRED"
        else:
            return "EXPIRED"

    def getclassfication(self):

        left = self.asst.deadline - timezone.now()

        if timezone.now() < self.asst.deadline :
            if(left.days < 3):
                return "URGENT"
            elif (left.days <=0):
                return "EXPIRED"
            else:
                return "OPEN"
        else:
            return "OPEN"

    def was_expired(self):
        return (self.asst.deadline - timezone.now())>0
    was_expired.boolean = False

class AssignedGroup(models.Model):
    group = models.ForeignKey(group)
    asst = models.ForeignKey(Assessment)



class Event(models.Model):
    from_user = models.ForeignKey(User, related_name='relationships')
    to_user = models.ForeignKey(User, related_name='related_to')
    event = models.CharField(max_length="50")
    when = models.DateTimeField('Date happened')

    def duration(self):
        duration = timezone.now() - self.when

        if (duration.days > 0):
            return str(duration.days) +" days ago"
        elif ((duration.seconds//3600) >0):
            return str((duration.seconds//3600)) + " hr(s) ago"  
        elif ((duration.seconds//60)%60 >0):
            return str((duration.seconds//60)%60 ) + " min(s) ago"      
        elif (duration.seconds < 60):
            return str(duration.seconds) +" seconds ago"
        else:
            return "UNDFINED"

    def __str__(self):
        return str(self.from_user.username) + " " +str(self.to_user.username) +" "+str(self.event)

mcq_platform/mcq/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)
    message = forms.CharField(widget=forms.Textarea(), max_length=1000)

mcq_platform/mcq/templates/embed/asst_public.html
{% extends "mcq/user_base.html" %}
   

   {% load static %}



{% block css %}


 

{% endblock %}

 {% block sidebar %}

 
              
                  <li class="mt">
                      <a id="nav_homepage" href="/mcq/">
                          <i class="fa fa-dashboard"></i>
                          <span>Dashboard</span>
                      </a>
                  </li>

                  <li  class="sub-menu">
                      <a id="nav_homepage" href="/mcq/">
                          <i class="fa fa-dashboard"></i>
                          <span>My Group</span>
                      </a>
                  </li>


                  <li class="sub-menu">
                      <a href="javascript:;" class="active" >
                          <i class="fa fa-desktop"></i>
                          <span>My Assessments</span>
                      </a>
                      <ul class="sub">

                          <li class="active"><a  href="{% url 'mcq:asstlist'  %}">Assessment List</a></li>
                          <li><a  href="{% url 'mcq:asstresult'  %}">Assessment Result</a></li>
                      </ul>
                  </li>

                  <li class="sub-menu">
                      <a href="/course/" >
                          <i class="fa fa-bar-chart-o"></i>
                          <span>Statistics</span>
                      </a>
          <ul class="sub">
                        <li><a  href="/general_review_list">View Statistics</a></li>
                    </ul>
                  </li>



   {% endblock %}






       {% block content %}



{% if asst.assessment_type == 0%}


  <div class="col-md-12 mt">
                      <div class="content-panel">
                            <table class="table table-hover">
                        
   <h3><i class="fa fa-angle-right"></i> Assessment Page for:</h3>
                             <h2><center><strong>{{ asst.assessment_name }}</strong></center></h2>


                       

                            <hr>

                                <thead>
                                <tr>
                                    <th >Name</th>

                                     <th>Description</th>
                                    
                                    <th  class="col-sm-1">MCQs</th>
                                    <th  class="col-sm-2">Publish date</th>
                                </tr>
                                </thead>
                                <tbody>
                                

             
 <tr>
                                    <td>{{asst.assessment_name}}</td>
                               
                                    <td>{{asst.assessment_description}}</td>
                           

                                    <td>{{ asst.mcq_num }}</td>
                                    <td>{{asst.pub_date}}</td>
                                     </tr>
                    
                               
                        
                                </tbody>
                            </table>
                        </div><! --/content-panel -->
                    </div><!-- /col-md-12 -->


{% for question in p %}
<form action="{% url 'mcq:vote' question.id %}" method="post">

{% csrf_token %}
                    <div class="col-md-12 mt">
                      <div class="content-panel">
                        
                            <h3><i class="fa fa-angle-right"></i>

                           <a href="{% url 'mcq:mcqstats' question.id %}"> {{ question.question_text }}</a></h3>
                       

                            <hr>

                  <div class="form-panel">                  

<div >
                {% for choice in question.choice_set.all %}

                                    {{choice.answer_code}}.

                                    {% if question.question_type == 1%}
                             <input type="checkbox" name="question{{question.id}}[]" id="choice{{ forloop.counter }}" value="{{ choice.answer_code }}" />
                                {% else %}
                                 <input type="radio" name="question{{question.id}}[]" id="{{ choice.answer_code }}" value="{{ choice.answer_code }}" />
{% endif %}



        <label name="showanswer{{question.id}}" hidden>

                                     {% if choice.is_correct%}
                                    <font color=red>✔</font>
                                    {% else %}
                                        ✘
                                    {% endif %}
</label>



                                     <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
                                     
                            {% endfor %}
  </div>                             

 





      <button type="button" id="grade{{question.id}}" class="btn btn-theme02" >Grade </button> 
      <div id="expand{{question.id}}" hidden>
      <button type="button" id="again{{question.id}}" class="btn btn-theme03 " >Again</button> 


      {% if question.question_type == 0 or  question.question_type == 2%}
      <button type="button" id="solution{{question.id}}" class="btn btn-theme04 " >Solution </button> 
      {% endif %}
 {% if question.question_type == 1%}
      <button type="button" id="solution{{question.id}}"  class="btn btn-theme04 " >Solution </button> 
      {% endif %}

    </div>



            <p id="msg-success{{question.id}}" class="alert alert-success" hidden></p>
            <p id="msg-wrong{{question.id}}" class="alert alert-danger" hidden></p>
  </div>
                        </div><! --/content-panel -->
                    </div><!-- /col-md-12 -->


</form>
  
{% endfor %}


{% endif %}




{% if asst.assessment_type == 1%}




  <div class="col-md-12 mt">
                      <div class="content-panel">
                            <table class="table table-hover">
                        
   <h3><i class="fa fa-angle-right"></i> Assessment Page for:</h3>
                             <h2><center><strong>{{ asst.assessment_name }}</strong></center></h2>


                       

                            <hr>

                                <thead>
                                <tr>
                                    <th >Name</th>

                                     <th>Description</th>
                                    
                                    <th  class="col-sm-1">MCQs</th>
                                    <th  class="col-sm-2">Publish date</th>
                                </tr>
                                </thead>
                                <tbody>
                                

             
 <tr>
                                    <td>{{asst.assessment_name}}</td>
                               
                                    <td>{{asst.assessment_description}}</td>
                           

                                    <td>{{ asst.mcq_num }}</td>
                                    <td>{{asst.pub_date}}</td>
                                     </tr>
                    
                               
                        
                                </tbody>
                            </table>
                        </div><! --/content-panel -->
                    </div><!-- /col-md-12 -->

<form  onsubmit="return check_if_all_done(event)" action="" method="post">

    {% if errors %}
                {% for error in errors %}
        <li>

             <p style="color: red;">
                Please correct the error: {{error}} below.
             </p>
            
        </li>
          {% endfor %}
    {% endif %}


{% for question in p %}

{% csrf_token %}
                    <div class="col-md-12 mt">
                      <div class="content-panel">
                        
                            <h4><i class="fa fa-angle-right"></i>

                        Question #{{forloop.counter}}:   <a href="{% url 'mcq:mcqstats' question.id %}"> {{ question.question_text }}</a></h4>
                       

                            <hr>

                  <div class="form-panel">                  

<div >
                {% for choice in question.choice_set.all %}

                                    {{choice.answer_code}}.

                                    {% if question.question_type == 1%}
                             <input type="checkbox" name="question{{question.id}}" id="choice{{ forloop.counter }}" value="{{ choice.answer_code }}" />
                                {% else %}
                                 <input type="radio" name="question{{question.id}}" id="{{ choice.answer_code }}" value="{{ choice.answer_code }}" />
{% endif %}

      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />

        


{% if asst.assessment_type == 1%}



{% endif %}




                                     <br>
                                     
                            {% endfor %}
  </div>                             

 




  </div>
                        </div><! --/content-panel -->
                    </div><!-- /col-md-12 -->



  
{% endfor %}


  <div class="col-md-12 mt">


                          
                                    
                                          <button class="btn btn-theme02"  type="submit" id="submit">Submit</button>
                                          <a href="/mcq/admin/mcqcollection/create_mcq/" role="button" class="btn btn-theme04">Back</a>
                                     
                                
                                </div>
</form>





{% endif %}


        {% endblock %}




    {% block js %}


{% if asst.assessment_type == 1%}

<script type="text/javascript">
function check_if_all_done(e) {

  {% for question in p %}

  if ($('input[name=question{{question.id}}]:checked').length === 0) {
      e.preventDefault();

      alert("You haven't completed Question #{{forloop.counter}}.");
      return false;
  }


  {% endfor %}

}
</script>


{% endif %}
{% if asst.assessment_type == 0%}
  <script>


{% for question in p %}



$("#grade{{question.id}}").click(function() {

   $('#grade{{question.id}}').hide();
 document.getElementById('expand{{question.id}}').hidden=false;


{% if question.question_type != 1%}
    var value = $('input[name=question{{question.id}}]:checked').val()
 {% else %}
var value = $.map($(':checkbox[name=question{{question.id}}\\[\\]]:checked'), function(n, i){
      return n.value;
}).join('');

 {% endif %}


    if(value == "{{question.correct_answer}}"){


   document.getElementById('msg-success{{question.id}}').hidden=false;
   document.getElementById('msg-wrong{{question.id}}').hidden=true;
   document.getElementById('msg-success{{question.id}}').innerHTML = "Great Job!<br> {{question.explanation}}";

    }else{


   document.getElementById('msg-success{{question.id}}').hidden=true;
    document.getElementById('msg-wrong{{question.id}}').hidden=false;
    document.getElementById('msg-wrong{{question.id}}').innerHTML = "Tty again! <br> Hints: {{question.hints}}";


    }

});


$("#again{{question.id}}").click(function() {
$('#grade{{question.id}}').show();
 document.getElementById('expand{{question.id}}').hidden=true;

   document.getElementById('msg-success{{question.id}}').hidden=true;
    document.getElementById('msg-wrong{{question.id}}').hidden=true;


{% if question.question_type == 1%}
var value = $.map($(':checkbox[name=question{{question.id}}\\[\\]]:checked'), function(n, i){
  n.checked = false;

      return n.value;
})
{% else %}


var value = $.map($(':radio[name=question{{question.id}}\\[\\]]:checked'), function(n, i){
  n.checked = false;

      return n.value;
})
{% endif %}

var length = document.getElementsByName("showanswer{{question.id}}").length
 for(i=0;i<length;i++){
document.getElementsByName("showanswer{{question.id}}").item(i).hidden = true;

}

});




$("#solution{{question.id}}").click(function() {

var length = document.getElementsByName("showanswer{{question.id}}").length
 for(i=0;i<length;i++){
document.getElementsByName("showanswer{{question.id}}").item(i).hidden = false;

}
});








{% endfor %}






</script>



  <script src="{% static "assets/js/bootstrap-switch.js" %}"></script>
{% endif %}







    {% endblock %}

mcq_platform/mcq/templates/embed/embed_mcq.html
{% extends "embed/embed_base.html" %}
   

   {% load static %}



{% block css %}


 

{% endblock %}





       {% block content %}












<form  onsubmit="return check_if_all_done(event)" action="" method="post">

    {% if errors %}
                {% for error in errors %}
        <li>

             <p style="color: red;">
                Please correct the error: {{error}} below.
             </p>
            
        </li>
          {% endfor %}
    {% endif %}




{% csrf_token %}


                    <div class="col-md-12 mt">
                      <div class="content-panel">
                        
                            <h4><i class="fa fa-angle-right"></i>

                        Question :   {{ question.question_text }}</h4>
                       

                            <hr>

                  <div class="form-panel">                  

<div >
                {% for choice in question.choice_set.all %}

                                    {{choice.answer_code}}.

                                    {% if question.question_type == 1%}
                             <input type="checkbox" name="{{question.id}}" id="choice{{ forloop.counter }}" value="{{ choice.answer_code }}" />
                                {% else %}
                                 <input type="radio" name="{{question.id}}" id="{{ choice.answer_code }}" value="{{ choice.answer_code}}" />
{% endif %}

      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />

        


{% if asst.assessment_type == 1%}



{% endif %}




                                     <br>
                                     
                            {% endfor %}
  </div>                             

 




  </div>
                        </div><! --/content-panel -->
                    </div><!-- /col-md-12 -->



  



  <div class="col-md-12 mt">


                          
                                    
                                          <button class="btn btn-theme02"  type="submit" id="submit">Submit</button>
                                         
                                     
                                
                                </div>
</form>







        {% endblock %}




    {% block js %}


<script type="text/javascript">
function check_if_all_done(e) {



  if ($('input[name={{question.id}}]:checked').length === 0) {
      e.preventDefault();

      alert("You haven't completed the question!");
      return false;
  }



}
</script>





    {% endblock %}

mcq_platform/mcq/templates/embed/embed_success.html
{% extends "embed/embed_base.html" %}
   

   {% load static %}



{% block css %}


 

{% endblock %}





       {% block content %}









<p>success!</p>




        {% endblock %}




    {% block js %}





    {% endblock %}

mcq_platform/mcq/templates/embed/embed_success副本.html
MY NAME IS DA DENG 

<iframe width="600" height="500" frameBorder="0"src="http://127.0.0.1:8000/mcq/embed/4/"></iframe>