mcq_platform/mcq/urls.py
from django.conf.urls import url

from . import views

# urlpatterns = [
#     url(r'^$', views.index, name='index'),
#     # ex: /polls/5/
#     url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
#     # ex: /polls/5/vote/
#     url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
# ]

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^asstlist/$', views.AsstListView.as_view(), name='asstlist'),
    url(r'^asstresult/$', views.AsstResultView.as_view(), name='asstresult'),
    url(r'^asstdetail/(?P<assessment_id>[0-9]+)/$', views.UserAsstDetail, name='userasstdetail'),
    url(r'^asstresult/(?P<assessment_id>[0-9]+)/$', views.UserAsstResult, name='userasstresult'),

    url(r'^admin/$', views.AdminIndex, name='mcqadmin'),
    
    url(r'^admin/labellist/$', views.SubjectListView, name='subjectlist'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^admin/labellist/create_label/$',views.SubjectCreation,name = 'labelcreation'),
    url(r'^admin/labellist/edit/(?P<label_id>[0-9]+)/$',views.LabelEdit,name = 'labeledit'),


    url(r'^index/$', views.index, name='index'),
    url(r'^hello/$', views.hello, name='hello'),

    url(r'^profile/(.+)/$', views.profile,name="userprofile"),

    url(r'^admin/mcqcollection/$', views.McqCollectionView.as_view(), name='mcqcollection'),
    url(r'^admin/mcqcollection/create_mcq/$',views.McqOption,name = 'mcqoption'),
    url(r'^admin/mcqcollection/edit/(?P<question_id>[0-9]+)/$',views.McqEdit,name = 'mcqedit'),
    url(r'^admin/mcqcollection/replica/(?P<asst_id>[0-9]+)/(?P<question_id>[0-9]+)/$',views.McqReplica,name = 'mcqreplica'),
   
    url(r'^admin/mcqcollection/create_mcq/(?P<option>[0-3]{1})/$',views.McqCreation,name = 'mcqcreation'),
 
    url(r'^admin/bundlecollection/create_bundle/$',views.BundleCreation,name = 'bundlecreation'),
    url(r'^admin/bundlecollection/$', views.BundleCollectionView.as_view(), name='bundlecollection'),
    url(r'^admin/bundlecollection/(?P<bundle_id>[0-9]+)/$',views.BundleDetail,name = 'bundlecdetail'),
    url(r'^admin/bundlecollection/edit/(?P<bundle_id>[0-9]+)/$',views.BundleEdit,name = 'bundleedit'),
  
    url(r'^admin/asstcollection/create_asst/$',views.AsstCreation,name = 'asstcreation'),
    url(r'^admin/asstallocation/$',views.AsstAllocation,name = 'asstallocation'),
    url(r'^admin/asstcollection/$', views.AsstCollectionView.as_view(), name='asstcollection'),
    url(r'^admin/asstcollection/edit/(?P<asst_id>[0-9]+)/$',views.AsstEdit,name = 'asstedit'),

    url(r'^admin/statistics/mcq/(?P<question_id>[0-9]+)/$', views.McqStatsView, name='mcqstats'),
    url(r'^admin/statistics/asst/(?P<assessment_id>[0-9]+)/$', views.AsstStatsView, name='asststats'),
    url(r'^ajax_deal/$',views.ajax_deal,name='ajax'),
    url(r'^ccc/$',views.ccc,name="ccc"),

    url(r'^tt/$',views.tt,name="tt"),

    url(r'^embed/(?P<question_id>[0-9]+)/$', views.EmbedMcq, name='embedmcq'),

]

mcq_platform/mcq_platform/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'mcq_platform.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^mcq/', include('mcq.urls',namespace ="mcq")),
    url(r'^admin/', include(admin.site.urls)),
]

mcq_platform/mcq/models.py
from django.db import models
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.


# For storing user profile
from django.contrib.auth.models import User
from django.db.models.signals import post_save




class UserProfile(models.Model):
    # This field is required.
    user = models.OneToOneField(User)

    # Other fields here
    num_completed_asst = models.IntegerField(default = 0)
    num_incomplete_asst = models.IntegerField(default = 0)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)


class Category(models.Model):
    category_code = models.CharField(max_length = 8,default = "11")
    category_name = models.CharField(max_length = 100)

    def __str__(self):              # __unicode__ on Python 2
        return self.category_code

ASST_CHOICES = (
    (0, 'practical exercise'),
    (1, 'formal exam'),
)

ASST_STATUS = (
    (0, 'OPEN'),
    (1, 'CLOSED'),
)

QUESTION_TYPES = (
    (0,'Single Answers'),
    (1,'Multiple Answers'),
    (2,'True/False'),
    (3,'Input'),
    (4,'undefined')
)

#feedback
class Question(models.Model):
    category = models.ManyToManyField(Category)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    question_type = models.IntegerField(choices = QUESTION_TYPES,default = 0)
    correct_answer = models.CharField(max_length =100,default=0)
    explanation = models.CharField(max_length =100,default="undefined")
    input_answer = models.CharField(max_length = 100,default=0)
    hints = models.CharField(max_length =100,default="No hints.")
    is_replica = models.BooleanField(default=False)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):              # __unicode__ on Python 2
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question)    
    answer_code = models.CharField(max_length = 10)
    is_correct = models.BooleanField(default= False)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):              # __unicode__ on Python 2
        return self.choice_text +" "+str(self.votes)

class PublicResult(models.Model):
    question = models.ForeignKey(Question)
    num_of_correct_attempts = models.IntegerField(default=0)
    num_of_incorrect_attempts = models.IntegerField(default=0)
    def __str__(self):              # __unicode__ on Python 2
        return self.question.question_text


def create_question(sender, instance, created, **kwargs):
    if created:
        PublicResult.objects.create(question=instance)

post_save.connect(create_question, sender=Question)

#total score out of
class Bundle(models.Model):
    question = models.ManyToManyField(Question)
   # category = models.ForeignKey(Category)
    bundle_name = models.CharField(max_length = 100)
    bundle_desc = models.CharField(max_length = 200,default="undefined")
    pub_date = models.DateTimeField('date published')
    total_question_num = models.IntegerField(default=0)
   # bundle_type = models.IntegerField(choices = BUNDLE_CHOICES,default = 0)
    #question_total_num = models.IntegerField(default = 1)
    #total_allocated = models.IntegerField(default = 0)
    #completed_num = models.IntegerField(default = 0)
    #pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.bundle_name



class Assessment(models.Model):
    question = models.ManyToManyField(Question, related_name='asstquestion')
    publisher = models.ForeignKey(User)
    category = models.ForeignKey(Category,null=True)
    assessment_name = models.CharField(max_length = 100,default=0)
    assessment_type = models.IntegerField(choices = ASST_CHOICES,default = 0)
    assessment_description = models.CharField(max_length = 200,default= "undefined")
    duration = models.IntegerField(default = 0)#mins  
    mcq_num = models.IntegerField(default = 0)
    points = models.IntegerField(default = 0)
    pub_date = models.DateTimeField('date published',default=None)
    deadline = models.DateTimeField('deadline')
    status = models.IntegerField(choices = ASST_STATUS,default = 0)
    


    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.assessment_name

class ChoiceAsstStats(models.Model):
    choice = models.ForeignKey(Choice)
    question = models.ForeignKey(Question)
    asst = models.ForeignKey(Assessment)
    votes = models.IntegerField(default=0)
    def __str__(self):              # __unicode__ on Python 2
        return self.choice.choice_text

class AssessmentQuestion(models.Model):
    asst_question = models.ForeignKey(Assessment)
    question = models.ForeignKey(Question)
    question_type = models.IntegerField(default=4)
   



class QuestionAttempt(models.Model):
    assessment = models.ForeignKey(Assessment)
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    user_answer = models.CharField(max_length = 10)
    is_correct = models.NullBooleanField(null=True)
    def __str__(self):
        return self.assessment.assessment_name + " " + self.user.username + " " + str(self.question.pk)


class AsstResult(models.Model):
    assessment = models.ForeignKey(Assessment)
    user = models.ForeignKey(User)
    score = models.IntegerField(default = 0)
    grade = models.CharField(max_length = 50,default="Undefined" )
    def __str__(self):
        return str(self.user.username)+"-"+str(self.assessment.assessment_name)



class group(models.Model):
    group_name = models.CharField(max_length = 20)
    creation_date = models.DateTimeField('date published')


class AllocationRecord(models.Model):
    asst = models.ForeignKey(Assessment)
    staff = models.ForeignKey(User)
    when = models.DateTimeField('Date allocated')
    def __str__(self):
        return str(self.staff.username)+"-"+str(self.asst.assessment_name)

class AssignedAsst(models.Model):
    asst = models.ForeignKey(Assessment)
    user = models.ForeignKey(User, related_name='to_user')
    from_user = models.ForeignKey(User, related_name='from_user')
    is_done = models.BooleanField(default= False) 
    def __str__(self):
        return (str(self.user.pk)+str(self.asst.assessment_name))

    def getAsstName(self):
        return str(self.asst.assessment_name)

    def dayCounter(self):
        left = self.asst.deadline - timezone.now()

        if timezone.now() < self.asst.deadline :
            if(left.days > 0):
                return str(left.days) + " day(s) left"
            elif ((left.seconds//3600) >0):
                return str((left.seconds//3600)) + " hr(s) left"
            elif ((left.seconds//60)%60 >0):
                return str((left.seconds//60)%60 ) + " min(s) left"
            else:
                return "EXPIRED"
        else:
            return "EXPIRED"

    def getclassfication(self):

        left = self.asst.deadline - timezone.now()

        if timezone.now() < self.asst.deadline :
            if(left.days < 3):
                return "URGENT"
            elif (left.days <=0):
                return "EXPIRED"
            else:
                return "OPEN"
        else:
            return "OPEN"

    def was_expired(self):
        return (self.asst.deadline - timezone.now())>0
    was_expired.boolean = False

class AssignedGroup(models.Model):
    group = models.ForeignKey(group)
    asst = models.ForeignKey(Assessment)



class Event(models.Model):
    from_user = models.ForeignKey(User, related_name='relationships')
    to_user = models.ForeignKey(User, related_name='related_to')
    event = models.CharField(max_length="50")
    when = models.DateTimeField('Date happened')

    def duration(self):
        duration = timezone.now() - self.when

        if (duration.days > 0):
            return str(duration.days) +" days ago"
        elif ((duration.seconds//3600) >0):
            return str((duration.seconds//3600)) + " hr(s) ago"  
        elif ((duration.seconds//60)%60 >0):
            return str((duration.seconds//60)%60 ) + " min(s) ago"      
        elif (duration.seconds < 60):
            return str(duration.seconds) +" seconds ago"
        else:
            return "UNDFINED"

    def __str__(self):
        return str(self.from_user.username) + " " +str(self.to_user.username) +" "+str(self.event)

mcq_platform/mcq/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)
    message = forms.CharField(widget=forms.Textarea(), max_length=1000)

mcq_platform/mcq/templates/mcq/asst_creation.html
{% extends "mcq/base.html" %}
   
{% load static %}


{% block css%}


  

    <link rel="stylesheet" type="text/css" href="{% static "assets/js/bootstrap-datetimepicker/css/datetimepicker.css" %}" />

{% endblock%}

 {% block sidebar %}

 
                    
                  <li class="mt">
                      <a id="nav_homepage" href="{% url 'mcq:mcqadmin'  %}">
                          <i class="fa fa-dashboard"></i>
                          <span>Dashboard</span>
                      </a>
                  </li>


                  <li class="sub-menu">
                      <a href="javascript:;" class="active" >
                          <i class="fa fa-desktop"></i>
                          <span>Management</span>
                      </a>
                      <ul class="sub" >

                          <li><a  href="{% url 'mcq:subjectlist'  %}">Label List</a></li>
                          <li><a  href="{% url 'mcq:mcqcollection'  %}">MCQ Collection</a></li>
                          <li ><a  href="{% url 'mcq:bundlecollection'  %}">MCQ Bundle</a></li>
                          <li class="active"><a  href="{% url 'mcq:asstcollection'  %}">Assessment</a></li>
                      </ul>
                  </li>

                  <li class="sub-menu">
                      <a href="/course/" >
                          <i class="fa fa-bar-chart-o"></i>
                          <span>Statistics</span>
                      </a>
          <ul class="sub">
                        <li><a  href="/general_review_list">View Statistics</a></li>
                    </ul>
                  </li>
               
            


   {% endblock %}






  {% block content %}



  <!-- FORM VALIDATION -->
              <div class="row mt">
                  <div class="col-lg-12">
                      <h4><i class="fa fa-angle-right"></i> Create a new assessment</h4>
                      <div class="form-panel">
                          <div class=" form">
                              <form class="cmxform form-horizontal style-form" id="asstform" method="POST" action="{% url 'mcq:asstcreation'  %}">

{% csrf_token %}


    {% if errors %}
                {% for error in errors %}
        <li>

             <p style="color: red;">
                Please correct the error: {{error}} below.
             </p>
            
        </li>
          {% endfor %}
    {% endif %}




                                  <div class="form-group ">
                                      <label for="cname" class="control-label col-lg-2">Assessment Title (required)</label>
                                      <div class="col-lg-10">
                                          <input class=" form-control" id="cname" name="asstTitle" minlength="2" type="text" required />
                                      </div>
                                  </div>



          <div class="form-group ">
               <label for="cname" class="control-label col-lg-2">Select assessment type</label>
                    <div class="col-lg-10" >
                                            <select class="form-control" name="asstType">

                                  
                                      <option value="0">Practical exam</option>
                                      <option value="1"> Formal EXAM</option>

                                
   
            </select>  
              </div>
             </div>




                       <div class="form-group ">
               <label for="cname" class="control-label col-lg-2">Select subject</label>
                    <div class="col-lg-10" >
                                            <select class="form-control" name="asstSubject">

                                              {% if subject_list %}
                                    {% for subject in subject_list %}
                                      <option value="{{subject.pk}}">


{{subject.category_code}}</option>

                                    {% endfor%}
                                    {% endif %}
   
            </select>  
              </div>
             </div>


  <div class="form-group ">
                                      <label for="uni_id" class="control-label col-lg-2">Time duration (mins)</label>
                                      <div class="col-lg-2">
                                          <input type="text" class="form-control bfh-phone" id="uniid" name = "asstDuration" placeholder ="Example: 120" data-format="ddd" required>
                                      </div>
                                  </div>


  <div class="form-group">
                                  <label class="control-label col-md-3">Default input Datetimepicker</label>
                                  <div class="col-md-4">
                                      <input size="16" type="text" value="2015-12-01 10:00" class="form_datetime form-control" name="deadline">
                                  </div>
                              </div>

  

                                  <div class="form-group ">
                                      <label for="cname" class="control-label col-lg-2">Assessment Description (required)</label>
                                      <div class="col-lg-10">

<textarea name="asstDesc" class="form-control" rows="3" required></textarea>
                                        
                                      </div>
                                  </div>






        <div class="form-group " >
               <label for="cname" class="control-label col-lg-2">Select question options</p></label>
                    <div class="col-lg-10" >
                                            <select class="form-control" name="selectquestionoption" id="selectquestionoption"required >
                                            <option></option>
                                      <option value="1"> Select questions from bundle</option>
                                      <option value="2"> Select questions from MCQ collection</option>
                                      <option value="3"> Select questions from both</option>
                                   
   
            </select>  
              </div>
             </div>

 

        <div class="form-group "  id = "bundleselectionoption" hidden>
               <label for="cname" class="control-label col-lg-2">Select Bundle<p>(Win:Hold ctrl or MAC:Hold Command to multi-select</p></label>
                    <div class="col-lg-10" >
                                            <select class="form-control" name="asstBundle" multiple size='10' id ="bundleselector">

                                              {% if bundle_list %}
                                    {% for bundle in bundle_list %}
                                      <option value="{{bundle.pk}}">


{{bundle.bundle_name}}</option>

                                    {% endfor%}
                                    {% endif %}
   
            </select>  
              </div>
             </div>





        <div class="form-group " id = "questionselectionoption" hidden>
               <label for="cname" class="control-label col-lg-2">Select question<p>(Win:Hold ctrl or MAC:Hold Command to multi-select</p></label>
                    <div class="col-lg-10" >
                                            <select class="form-control" name="asstQuestion" multiple size='10' id ="questionselector">

                                              {% if question_list %}
                                    {% for question in question_list %}
                                      <option value="{{question.pk}}">


{{question.question_text}}</option>

                                    {% endfor%}
                                    {% endif %}
   
            </select>  
              </div>
             </div>





                             

                          



                                  <div class="form-group">
                                      <div class="col-lg-offset-2 col-lg-10">
                                          <button class="btn btn-theme" type="submit" id="submit">Save</button>
                                          <a href="/mcq/asstcollection/create_asst/" role="button" class="btn btn-theme04">Back</a>
                                      </div>
                                  </div>
                              </form>
                          </div>
                      </div><!-- /form-panel -->
                  </div><!-- /col-lg-12 -->
              </div><!-- /row -->















  {% endblock %}


    {% block js %}


   <script type="text/javascript" src="{% static "assets/js/bootstrap-formhelpers.min.js" %}"></script>
      <script type="text/javascript" src="{% static "assets/js/bootstrap-formhelpers.js" %}"></script>
     
     

      <script type="text/javascript" src="{% static "assets/js/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js" %}"></script>



    <script type="text/javascript" src="{% static "assets/js/advanced-form-components.js"%}"></script>
  
  

    {% endblock %}


   
          {% block script %}

<script>
      $(document).ready(function() {


$('#selectquestionoption').on('change', function() {

if ($(this).val() == "1"){
      $('#questionselectionoption').hide("slow");
      $('#bundleselectionoption').show("slow");
      $('#bundleselector').prop('required',true);
      $('#questionselector').prop('required',false);
}

if ($(this).val() == "2"){
      $('#questionselectionoption').show("slow");
      $('#bundleselectionoption').hide("slow");
      $('#bundleselector').prop('required',false);
      $('#questionselector').prop('required',true);
}

if ($(this).val() == "3"){
      $('#questionselectionoption').show("slow");
      $('#bundleselectionoption').show("slow");
      $('#questionselector').prop('required',true);
      $('#bundleselector').prop('required',true);
}



})

})
</script>

   
        {% endblock %}

mcq_platform/mcq/templates/mcq/asst_edit.html
{% extends "mcq/base.html" %}
   
{% load static %}


{% block css%}


  

    <link rel="stylesheet" type="text/css" href="{% static "assets/js/bootstrap-datetimepicker/css/datetimepicker.css" %}" />

{% endblock%}

 {% block sidebar %}

 
                    
                  <li class="mt">
                      <a id="nav_homepage" href="{% url 'mcq:mcqadmin'  %}">
                          <i class="fa fa-dashboard"></i>
                          <span>Dashboard</span>
                      </a>
                  </li>


                  <li class="sub-menu">
                      <a href="javascript:;" class="active" >
                          <i class="fa fa-desktop"></i>
                          <span>Management</span>
                      </a>
                      <ul class="sub" >

                          <li><a  href="{% url 'mcq:subjectlist'  %}">Label List</a></li>
                          <li><a  href="{% url 'mcq:mcqcollection'  %}">MCQ Collection</a></li>
                          <li ><a  href="{% url 'mcq:bundlecollection'  %}">MCQ Bundle</a></li>
                          <li class="active"><a  href="{% url 'mcq:asstcollection'  %}">Assessment</a></li>
                      </ul>
                  </li>

                  <li class="sub-menu">
                      <a href="/course/" >
                          <i class="fa fa-bar-chart-o"></i>
                          <span>Statistics</span>
                      </a>
          <ul class="sub">
                        <li><a  href="/general_review_list">View Statistics</a></li>
                    </ul>
                  </li>
               
            


   {% endblock %}






  {% block content %}



  <!-- FORM VALIDATION -->
              <div class="row mt">
                  <div class="col-lg-12">
                      <h4><i class="fa fa-angle-right"></i> Create a new assessment</h4>
                      <div class="form-panel">
                          <div class=" form">
                              <form class="cmxform form-horizontal style-form" id="asstform" method="POST" action="{% url 'mcq:asstedit' asst.id%}" >

{% csrf_token %}


    {% if errors %}
                {% for error in errors %}
        <li>

             <p style="color: red;">
                Please correct the error: {{error}} below.
             </p>
            
        </li>
          {% endfor %}
    {% endif %}




                                  <div class="form-group ">
                                      <label for="cname" class="control-label col-lg-2">Assessment Title (required)</label>
                                      <div class="col-lg-10">
                                          <input class=" form-control" id="cname" name="asstTitle" minlength="2" type="text" value="{{asst.assessment_name}}"required />
                                      </div>
                                  </div>



          <div class="form-group ">
               <label for="cname" class="control-label col-lg-2">Select assessment type</label>
                    <div class="col-lg-10" >
                                            <select class="form-control" name="asstType">

                                         {% if asst.assessment_type == 0 %}}
                                         <option value="0" selected>Practical exam</option>
                                         <option value="1"> Formal EXAM</option>
                                         {% else %}
                                       <option value="0">Practical exam</option>
                                      <option value="1" selected> Formal EXAM</option>
                                         {% endif %}
                                     

                                
   
            </select>  
              </div>
             </div>




                       <div class="form-group ">
               <label for="cname" class="control-label col-lg-2">Select label</label>
                    <div class="col-lg-10" >
                                            <select class="form-control" name="asstSubject">

                                              {% if subject_list %}
                                    {% for subject in subject_list %}
                                      <option value="{{subject.pk}}">


{{subject.category_code}}</option>

                                    {% endfor%}
                                    {% endif %}
   
            </select>  
              </div>
             </div>


  <div class="form-group ">
                                      <label for="uni_id" class="control-label col-lg-2">Time duration (mins)</label>
                                      <div class="col-lg-2">
                                          <input type="text" class="form-control bfh-phone" id="uniid" name = "asstDuration" value="{{asst.duration}}" data-format="ddd" required>
                                      </div>
                                  </div>


  <div class="form-group">
                                  <label class="control-label col-md-3">Default input Datetimepicker</label>
                                  <div class="col-md-4">
                                      <input size="16" type="text"  class="form_datetime form-control" name="deadline" value="{{asst.deadline|date:'Y-m-d H:i' }}">
                                  </div>
                              </div>

  

                                  <div class="form-group ">
                                      <label for="cname" class="control-label col-lg-2">Assessment Description (required)</label>
                                      <div class="col-lg-10">

<textarea name="asstDesc" class="form-control" rows="3" required>{{asst.assessment_description}}</textarea>
                                        
                                      </div>
                                  </div>






 <div class="form-group ">
               <label for="cname" class="control-label col-lg-2">Select MCQ<p>(Win:Hold ctrl or MAC:Hold Command to multi-select</p></label>
                    <div class="col-lg-10" >
                                            <select class="form-control" name="asstQuestion" multiple size='10'>

                                            
                                    {% for question in question_list  %}

{% if question in questionSet%}
                                      <option value="{{question.pk}}" selected>

{{question.question_text}}</option>
{%else%}
   <option value="{{question.pk}}" >        
{{question.question_text}}</option>
{% endif%}
                                    {% endfor%}
                                 
   
            </select>  
              </div>
             </div>

 









                             

                          



                                  <div class="form-group">
                                      <div class="col-lg-offset-2 col-lg-10">
                                          <button class="btn btn-theme" type="submit" id="submit">Save</button>
                                          <a href="{% url 'mcq:asststats' asst.id%}" role="button" class="btn btn-theme04">Back</a>
                                      </div>
                                  </div>
                              </form>
                          </div>
                      </div><!-- /form-panel -->
                  </div><!-- /col-lg-12 -->
              </div><!-- /row -->















  {% endblock %}


    {% block js %}


   <script type="text/javascript" src="{% static "assets/js/bootstrap-formhelpers.min.js" %}"></script>
      <script type="text/javascript" src="{% static "assets/js/bootstrap-formhelpers.js" %}"></script>
     
     

      <script type="text/javascript" src="{% static "assets/js/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js" %}"></script>



    <script type="text/javascript" src="{% static "assets/js/advanced-form-components.js"%}"></script>
  
  

    {% endblock %}


   

mcq_platform/mcq/templates/mcq/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'mcq:vote' question.id %}" method="post">

{% csrf_token %}
{% for choice in question.choice_set.all %}

    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{result}} {{correct_num}}{{ choice.choice_text }}</label><br />


{% endfor %}
<input type="submit" value="Vote" />
</form>